### ISSUE TITLE
アブストラクション中の言い回し

### ISSUE THREAD

**Issue by nanbuwks** [busyoucow/spaceBeans#15]
タンパク源摂取源

「源」が2回出ているので言い換えを。

**Comment by busyoucow** [comment]
そのような内容は確認できませんでした。
「結果としてタンパク質摂取源としては優秀だが～」

**Comment by nanbuwks** [comment]
確かめたところ、「タンパク源摂取源」と書いた履歴は確認できませんでした。幻だったようです。申し訳がございません!!
